build: use explicit versions for dependencies
Solar-network/python-crypto pull request #26
Opened 2022-05-31 19:10 UTC by c0nsol3

Tested on Python 3.6, 3,7, 3.8., 3.9 and 3.10

Tests pass on all above versions.

2022-06-02 21:38 UTC, c0nsol3 commented
@sleepdefic1t i've removed that commit and force pushed all changes w/o it.

2022-06-02 21:40 UTC, sleepdefic1t submitted a review, later dismissed

2022-06-03 13:51 UTC, sleepdefic1t requested changes

2022-06-03 14:34 UTC, sleepdefic1t approved these changes

2022-06-03 14:37 UTC, Cactus-15-49 approved these changes

2022-06-03 16:03 UTC, merged