feat: v3 solar transactions with bip340 schnorr sigs
Solar-network/python-crypto pull request #3
Opened 2022-05-22 17:26 UTC by c0nsol3

### Changes

- joined the schnorr legacny and bip340 schnorr under a unified signing and verifying functions so we dont have two separate functions
-  made V3 a default transaction version
- addedd `setVersion` method to transaction builder so anyoner using the library can override the default version when they build a transaction

### Other

All tests pass.

Example txs: [one](https://dexplorer.solar.org/transactions/d47ae1a16c27358351f7a52853c92c6d1c83d0f241a9155a0a469c11b97537c3), [two](https://dexplorer.solar.org/transactions/38d20222eb9c34c5869419597d4dc2583d79a0e724e4087f0b561320433538a4), [three](https://dexplorer.solar.org/transactions/75646a3c11cbc73fa670c57883ccec2889452ee9a88979aaa7dac65c740af10e)

2022-05-23 01:34 UTC, sleepdefic1t requested changes
- **Schnorr BIP340 Signatures**
    - **NON**-deterministic by default
    - deterministic option (ref: [core: crypto - hash.ts#L7](https://github.com/Solar-network/core/blob/develop/packages/crypto/src/crypto/hash.ts#L7))
- **Message Signing**
    - needs to be BIP340 Schnorr (not Ecdsa)

2022-05-23 06:28 UTC, c0nsol3 commented
I believe I've addressed everything in my latest commit. Let me know in case I missed something.

2022-05-23 19:46 UTC, sleepdefic1t requested changes

2022-05-23 19:46 UTC, sleepdefic1t commented on crypto/utils/message.py
> +    def sign(cls, message, passphrase, nonce=None):
- Remove deterministic option from Message signing
`def sign(cls, message, passphrase, nonce=None):` => `def sign(cls, message, passphrase):`

2022-05-23 20:07 UTC, sleepdefic1t approved these changes

2022-05-24 15:30 UTC, Cactus-15-49 approved these changes

2022-05-24 18:44 UTC, sleepdefic1t approved these changes

2022-05-24 18:45 UTC, merged